apiVersion: v1
kind: Secret
metadata:
  name: gitlab-ci-token
  namespace: kube-ops
  labels:
    app: gitlab-ci-runner
data:
  # echo token | base64 -w0
  GITLAB_CI_TOKEN: dFJmUHl6aUxVR3NqR21XNHM4eV8K