apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
  namespace: kube-ops
# ---
# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: gitlab-ci
#   namespace: kube-ops
# rules:
#   - apiGroups: [""]
#     resources: ["*"]
#     verbs: ["*"]
# ---
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: gitlab-ci
#   namespace: kube-ops
# subjects:
#   - kind: ServiceAccount
#     name: gitlab-ci
#     namespace: kube-ops
# roleRef:
#   kind: Role
#   name: gitlab-ci
#   apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab-ci
  namespace: kube-ops
subjects:
  - kind: ServiceAccount
    name: gitlab-ci
    namespace: kube-ops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io