apiVersion: v1
kind: Pod
metadata:
  name: sync-repo-volume-__CI_JOB_ID__
  namespace: airflow
spec:
  restartPolicy: Never
  containers:
  - name: git-clone
    image: alpine/git:1.0.7
    imagePullPolicy: IfNotPresent
    command:
      - /usr/local/git/git-clone.sh
      # - tail
    args:
      - "git@gitlab.51uuabc.com:data/airflowk8s.git"
      - "develop"
      - "/dags"
      # - -f
      # - /dev/null
    volumeMounts:
      - name: git-clone
        mountPath: /usr/local/git
      - name: airflow-dags
        mountPath: /dags
      - name: git-secret
        mountPath: /keys
  volumes:
  - name: airflow-dags
    persistentVolumeClaim:
      claimName: airflow-dags
  - name: git-secret
    secret:
      secretName: git-creds
      defaultMode: 288
  - name: git-clone
    configMap:
      name: git-clone
      defaultMode: 0755
