apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
data:
  # The sql_alchemy_conn value is a base64 encoded represenation of this connection string:
  # mysql://uuabc:UUbi-123@bd-dev-mysql:3306/airflow-k8s
  # echo "contet" | base64
  # base64 -d
  sql_alchemy_conn: bXlzcWw6Ly91dWFiYzpVVWJpLTEyM0BiZC1kZXYtbXlzcWw6MzMwNi9haXJmbG93LWs4cwo=
