apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  storageClassName: nfs-persistent
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-logs
  namespace: airflow
spec:
  storageClassName: nfs-persistent
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-workspaces
  namespace: airflow
spec:
  storageClassName: nfs-persistent
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
